* DELEGATOR
** ENG
*** General Info
   Delegator is continued work from To Do list created by grafitus - slava mu. It is very simple project management app. 
**** Curent version
     Delegator: spread communism 0.99
**** Functionality
    Basic functionality of delegator is to create simple Tasks that other members of forum can see and claim. Members can also be delegated to Tasks.
    Tasks are connected into Projects.

    Delegator also has many different views (and sortings) of tasks. You can select all tasks, tasks of specific project or specific members.
    Then you can select them depending on state (unfinished: unclaimed, claimed; finished: suddesful, unsuccesful, canceled).

    This basic options gives helps you organize and coordinate (political) actions.

*** ChangeLog
**** version 0.99
    Delegator gives basic functionality of simple project managment app. Current version is a mode for Simple Machines Forum (http://www.simplemachines.org/)
but it is intended to become a standalone app with SMF mode implementation. 
*** Authors
   Iskra - delovni odbor za tehnologijo (Iskra is a radical-left student organisation from Slovenia). Members of Technology Work Commitee of Iskra.
   http://studentska-iskra.org/
   
*** Install
**** SMF forum
   Download latest stable version from github (https://github.com/ivangrozni/smf-taskmanager).
   Create .zip file of delegator map and upload then install it to your SMF forum.
*** License
   This program is free software; you may redistribute it and/or modify it under 
   the terms of the provided license as published by Simple Machines LLC.          
                                                                                 
   This program is distributed in the hope that it is and will be useful, but  
   WITHOUT ANY WARRANTIES; without even any implied warranty of MERCHANTABILITY    
   or FITNESS FOR A PARTICULAR PURPOSE.                                            
                                                                                 
   See the "license.txt" file for details of the Simple Machines license.          
   The latest version can always be found at http://www.simplemachines.org. 
*** BUGS and TODOS
**** version 1.0
    - Delete/Edit Project
    - html anchoring (optional)
    - BBcode in description
    - cleaned up git repo

**** version 2.0
    - code cleanup (it complies with SMF standards)
    - statistical grafical elements (timelines, effectivity graphs...)
    - new form of Tasks (Tasks with duration)
    - notifications of coordinators

**** version 3.0
    - standalone version (GUI)
    - SMF implementation mod

** SLO
*** Splošne informacije
    Delegator je sloni na To Do list modu za SMF forum, ki ga je ustvaril grafitus - slava mu. Je zelo preprost program za projektno vodenje.
**** Trenutna verzija
     Delegator: spread communism 0.99
**** Funkcionalnost
     Osnovna funkcija Delegatorja je ustvarjanje preprostih zadolžitev. Uporabniki foruma lahko po zadolžitvah brskajo, jih sprejemajo in zaključujejo.
     Zadolžitve so povezane v Projekte.

     Delegator sestoji iz precej različnih pogledov. Gleda se lahko vse zadolžitve, zadolžitve posameznega projekta, ali zadolžitve posameznega uporabnika.
     Naprej lahko zadolžitve razdeliš glede na stanje.

     Ta funkcionalnost pomaga organizirati in koordinirati (politične) akcije.
     
*** Seznam Sprememb
**** verzija 0.99
     Delegator: spread communism 0.99 ima osnovno funkcionalnost preprostega programa za projektno vodenje. Trenutna verzija je vtičnik za
     Simple Machines Forum (http://www.simplemachines.org/), a namerava se ga razviti do te mere, da bo samostojna aplikacija z možnostjo
     implementacije na dotični forum.
*** Avtorji
    Iskra - delovni odbor za tehnologijo
    Iskra (http://studentska-iskra.org)
    Delovni odbor za tehnologijo (http://iskra.kreten.si)
*** Namestitev
**** SMF forum
     Končno verzijo potegnite z githuba (https://github.com/ivangrozni/smf-taskmanager).
     Ustvarite .zip datoteko iz mape delegator in jo nato naložite ter namestite na vaš SMF forum.
*** Licenca
    Ta program je prosta programska oprema; lahko se ga deli in/ali ureja v skladu s pogoji,
    ki jih določa Simple Machines LL.

    Ta program se distribuira v upanjum, da je in bo uporabe, a brez kakršnihkoli garancij.

    Vsi pogoji uporabe se nahajajo v "license.txt" dokumentu, katerega zadnjo verzijo lahko
    najdete na http://www.simplemachines.org
*** Hrošči in Izbolšave
**** verzija 1.0
     - Izpriši/Uredi Projekt
     - html anchoring (ne nujno)
     - BB koda v opisu projekta in zadolžitve
     - pospravi git odložišče

**** verzija 2.0
     - pospravi kodo, da bo ustrezala SMF standardom
     - statistični grafični elementi (časovnica, grafi efektivnosti ...)
     - nova oblika Zadolžitve (Zadolžitev s trajanjem)
     - opozorila za koordinatorje
       
**** verzija 3.0
     - samostojen program (s svojim grafičnim vmesnikom)
     - vtičnik za SMF forum
