#+TITLE: zapiski o delegatorju
#+SUBTITLE: random zapiski ob programiranju

* 160113

** DONE Ureditev delegatorja
   CLOSED: [2016-01-17 Sun 19:00]
   
*** DONE github commit
    CLOSED: [2016-01-17 Sun 19:00]
    Najprej bomo vse commital. 

*** DONE brisanje nepotrebnih stvari z gita
    CLOSED: [2016-01-17 Sun 19:00]
    Na gitu so kr eni SMF appi, ki so služili za osnovo in učenje.
    Dajmo to stran.

* 160117

** TODO Dokumentacija
   SCHEDULED: <2016-01-24 Sun>
   Uporabljam ta [[https://en.wikipedia.org/wiki/PHPDoc][phpDocumentor]].
   Vsak fajl in vsaka funkcija mora dobiti svoj opis.

   // phpDoc lahko s tabom raztegnem v zacetek dokumentacije.

** TODO Edit/delete project [0/2]
   SCHEDULED: <2016-01-24 Sun>
   V Delegator.php dodaj funkciji.

   V Delegator.templates.php dodaj gumbke. K Project_view (gumbek edit-proj in del-proj).
   Fora pa je, da naj jih vidi samo administrator.

   - [ ] delete-project
   - [ ] edit project

** TODO Coding guidelines [1/3]

   Gremo kodo spravit v obliko, kakržno zahteva ljudi na SMFju.
   [[http://wiki.simplemachines.org/smf/Coding_Guidelines][smf-coding-guidelines]]

   Veliko imam sorodnih funkcij.
   add_task_save, edit_task_save, super_edit_task, view_task
   add_project, edit_project, view_project

   Funkcije prikažejo isto vsebino, samo template je drugi.
   Zato je treba naredit listo vseh db requestov. 

   - [X] rename functions: ~add~ -> task, ~vt~ -> view-task, ~et~ -> edit-task
   - [ ] list of all database queries
   - [ ] remove database queries from template files
     
** TODO Commit v mod database
   
   Tole bomo dodali na tem linku:
   [[http://custom.simplemachines.org/mods/][dodaj-mod-na-smf]]

** Random bugi [0/2]
   
   - [ ] end-date se vnase narobe
   - [ ] opomba polje v log (kamor se bo zapisalo ime taska oz projekta)

* 160124
  Nadaljujem s prejšnjimi taski.

** TODO Permissions
   SCHEDULED: <2016-02-07 Sun>

   Par for je tukaj.
   - [ ] permission grupa
   - [ ] parmissions are working as they should be.

** narejeno

   - funkcija project_info
   - funkcija task_info (edit_task, super_edit_task, view_task)
   - iz template datoteke prenašam poizvedbe
